CREATE DATABASE Restaurant

USE Restaurant

CREATE TABLE Employees(
	DNI CHAR(9) NOT NULL,
	[Password] VARCHAR(30) NOT NULL,
	[Name] VARCHAR(30) NOT NULL,
	[Surname] VARCHAR(30) NOT NULL,
	NAF VARCHAR(12) NOT NULL,
	Birthday DATE NOT NULL,
	Position VARCHAR(13) NULL,
	Category VARCHAR(13) NULL,
	BankAccount CHAR(40) NULL
)


CREATE TABLE Payslips(
	ID INT IDENTITY NOT NULL,
	Salary MONEY NOT NULL
)

CREATE TABLE Schedules(
	ID INT IDENTITY NOT NULL,
	[WeekDay] VARCHAR(10) NOT NULL,
	StartDate SMALLDATETIME NOT NULL,
	EndDate SMALLDATETIME NOT NULL,
	Salary MONEY NOT NULL
)

CREATE TABLE Foods(
	ID INT IDENTITY NOT NULL,
	[Name] VARCHAR(20) NOT NULL,
	[Description] VARCHAR(30) NOT NULL,
	Price MONEY NULL,
	[Type] VARCHAR(9) NULL
)

CREATE TABLE Drinks(
	ID INT IDENTITY NOT NULL,
	[Name] VARCHAR(20) NOT NULL,
	[Description] VARCHAR(30) NOT NULL,
	Price MONEY NULL,
	Proof DECIMAL(2,1) NULL DEFAULT (0.0),
	Sparkling BIT NULL DEFAULT (0)
)

CREATE TABLE Allergies(
	ID INT IDENTITY NOT NULL,
	[Name] VARCHAR(12) NOT NULL
)


CREATE TABLE Products(
	ID INT IDENTITY NOT NULL,
	[Name] VARCHAR(20) NOT NULL,
	[Characteristics] VARCHAR(30) NOT NULL,
	Price MONEY NULL
)


CREATE TABLE Orders(
	ID INT IDENTITY NOT NULL,
	DateOrder SMALLDATETIME NOT NULL,
	[Sent] BIT NULL DEFAULT (0),
	Cancel BIT NULL DEFAULT (0)
)

CREATE TABLE OrdersLines(
	ID INT IDENTITY NOT NULL,
	IDOrder INT NOT NULL,
	IDProduct INT NOT NULL,
	Quantity INT NOT NULL
)

CREATE TABLE Receipts(
	ID INT IDENTITY NOT NULL,
	DateOfReceipt SMALLDATETIME NOT NULL,
	PaidFor BIT NULL DEFAULT (0)
)

CREATE TABLE ReceiptsLines(
	ID INT IDENTITY NOT NULL,
	IDReceipt INT NOT NULL,
	IDConsumable INT NOT NULL,
	Quantity INT NOT NULL
)








